name: Bump Semantic Version

on:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/check.yaml

  deploy:
    needs: check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create pull request with incremented tag
        id: run-tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
